#!/usr/bin/env bash
# You'll need to install plan9port https://github.com/9fans/plan9port

echo "++JOIN" $USER "from UNIX™!++" | 9p -a 'tcp!chat.9p.zone!9990' write chat
9p -a 'tcp!chat.9p.zone!9990' read chat &
while read l; do
	echo $LOGNAME : "$l"
done | 9p -a 'tcp!chat.9p.zone!9990' write chat

